### ISSUE TITLE
Doesn't Work inside VMs/VPS

### ISSUE THREAD

**Issue by thauanvargas** [SecHex/SecHex-Spoofy#13]
**Describe the bug**
So I don't know why it seems it doesn't work properly inside VMs or VPS
As of me I use Azure and have some Windows VPS there which I want to spoof some data, Spoofing All just makes so the vps is unreachable... And for VMs (VMWare) it turns off their internet.

**To Reproduce**
1. Use the GUI program inside a VM or VPS
2. Check internet connection or VPS shutting down your RDP
3. Restart VPS doesn't work neither, it just makes the VPS unusable.

**Expected behavior**
Work inside any VPS or VM

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Azure VPS
 - Browser Chrome Latest

**Comment by ItsMerkz** [comment]
Could I recommend you running this as admin for one and if that doesn't work make another issue, I will try to assist you
