### ISSUE TITLE
gpu uuid didnt work when executing, ty

### ISSUE THREAD

**Issue by ic4n911** [SecHex/SecHex-Spoofy#14]
**Describe the bug**
spoofed gpu uuid, and try to nvidia-smi -L, and the gpu uuid is still the same

**To Reproduce**
1. ran the code
2. spoofed gpu uuid
3. gpu uuid is still the same (checked with nvidia-smi -L)

**Expected behavior**
changing gpu uuid succesfully

**Screenshots**

**Desktop (please complete the following information):**
 - OS: win11 22h2 build 22621

**Comment by rhell5** [comment]
run in administrator

**Comment by ic4n911** [comment]
> run in administrator

still the same, checked with nvidia-smi -L

**Comment by Scrut1ny** [comment]
I checked the code and he HARD CODED his GPU registry data to this spoofer script instead of querying it.

**Comment by SecHex** [comment]
> 

That's true. The "Spoofer" is just a simple registry editor. Hardcoded functions and not a kernel spoofer. That's why most functions are only changed temporarily. Cheers!
