### ISSUE TITLE
If reinstall system, Still need to start over?

### ISSUE THREAD

**Issue by 1trapcode** [SecHex/SecHex-Spoofy#20]
Thanks for this great project.
But have one question.
If I reinstall windows in the future, will SecHex-Spoofy still work?
 Or will all HWIDs revert back to the original?

waiting for reply :)

**Comment by DoforY** [comment]
If reinstall windows all HWIDs revert back to the original

**Comment by SecHex** [comment]
> Thanks for this great project. But have one question. If I reinstall windows in the future, will SecHex-Spoofy still work? Or will all HWIDs revert back to the original?
> 
> waiting for reply :)

"Spoofy" is only manipulating the Serials of the Registry. After a factory reset, all Serials are original.
