### ISSUE TITLE
Which game will work with this ?

### ISSUE THREAD

**Issue by Jamoer** [SecHex/SecHex-Spoofy#23]
Does the CS GO can work with this ?

**Comment by ItzBlackStar** [comment]
from what I can tell it doesnt work at all. The HWID is still the same no matter what. (using python script to check)

**Comment by JohnnyWeston** [comment]
how about fortnite?

**Comment by SecHex** [comment]
Dont work for fortnite.

**Comment by Jamoer** [comment]
> from what I can tell it doesnt work at all. The HWID is still the same no matter what. (using python script to check)

i think it does on registrty level.. isnt it ?

**Comment by ItzBlackStar** [comment]
> > from what I can tell it doesnt work at all. The HWID is still the same no matter what. (using python script to check)
> 
> i think it does on registrty level.. doesnt it ? @SecHex

not for me, I dunno. In the end I used AMIDEWIN.exe and some other programs to change all my IDs. good luck with this one though, would be super useful <3

**Comment by Jamoer** [comment]
> > > from what I can tell it doesnt work at all. The HWID is still the same no matter what. (using python script to check)
> > 
> > 
> > i think it does on registrty level.. doesnt it ? @SecHex
> 
> not for me, I dunno. In the end I used AMIDEWIN.exe and some other programs to change all my IDs. good luck with this one though, would be super useful <3

well, my network was reseted tho, everytime i choose spoof all.... LOL
