### ISSUE TITLE
Disk spoofing is ineffective on Windows 11 22H2.

### ISSUE THREAD

**Issue by Zhen-Bo** [SecHex/SecHex-Spoofy#32]
**Describe the bug**
I tried to perform disk spoofing on Windows 11 22H2, and the log shows that the operation was successful. 
However, when I ran `wmic diskdrive get serialnumber`, I found that the serial number did not change at all.

**To Reproduce**
1. Execute `wmic diskdrive get serialnumber` and record the serial numbers of disk1 & disk2.
2. Open the GUI with administrator privileges and click on the DISK option.
3. After executing "wmic diskdrive get serialnumber" again, it was found that the displayed serial number is the same as the one recorded in step one.
4. In the log, only successful messages and before-after serial numbers are displayed, without any errors.

**Expected behavior**
The serial numbers of two SSDs have been changed.

**Desktop (please complete the following information):**
 - OS: Win11 22H2 Build 22621.2134
 - Version 1.5.6

**Comment by anonymusth** [comment]
same for me too

**Comment by SecHex** [comment]
It's just a registry change. Not ring0 change.
