### ISSUE TITLE
would it be possible to duplicate hwid?

### ISSUE THREAD

**Issue by kyloren23** [SecHex/SecHex-Spoofy#36]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
hi i bought a subscription program that only works on 1 hwid/pc 
if you try to use it on other computer it wont run.
is it possible to duplicate hwid of my pc to another pc? using this tool? or any method? thank you

**Comment by Scrut1ny** [comment]
No. Also this tool doesn't spoof HWIDs, only registry.
