### ISSUE TITLE
Sys not found error

### ISSUE THREAD

**Issue by 250mg** [SecHex/SecHex-Spoofy#39]
**Expected behavior**
SPoof disk worked before and now says this error

![Capture](https://github.com/SecHex/SecHex-Spoofy/assets/143553261/07b1ee32-e227-4b9a-ab8b-7c8846c73112)

 - WIN 10 home
 - firefox
 - 22H2

**Comment by pauloxota** [comment]
same error happened to me

**Comment by SecHex** [comment]
you can ignore this error. Its only for the "driver" function.
