### ISSUE TITLE
Make one for fortnite

### ISSUE THREAD

**Issue by 52skullz** [SecHex/SecHex-Spoofy#43]
i need one for fortnite

**Comment by MGTro** [comment]
me too fr fr ong no kizzy no cap

**Comment by ronnsex** [comment]
for fortnite, there is a temp one ( 3 hour). I use it because he make only safe software. 
https://discord.gg/kreyze

**Comment by SecHex** [comment]
> for fortnite, there is a temp one ( 3 hour). I use it because he make only safe software. https://discord.gg/kreyze

cringe bro.
