### ISSUE TITLE
Fivem spoofer not working "Service "Steam" was not found on computer"

### ISSUE THREAD

**Issue by sayit135** [SecHex/SecHex-Spoofy#58]
![image](https://github.com/SecHex/SecHex-Spoofy/assets/35692406/db3d044c-d699-48bd-99fa-0d455cd84421)
It gives me such a line, but I downloaded it normally and installed steam.

![image](https://github.com/SecHex/SecHex-Spoofy/assets/35692406/fcce2468-b91b-47c6-846a-676fef4a0937)

---------------------------------------------------------------------------------------------------------------------------------------
UEFI only boot mode. should we not do it?

**Comment by SecHex** [comment]
This function is currently in Maintenenace.

**Comment by sayit135** [comment]
When is it going to end

**Comment by Crex4k** [comment]
When the Maintenenace is done.

**Comment by SecHex** [comment]
fixed.
