### ISSUE TITLE
Fivem spoofer not working "Service "Steam" was not found on computer"

### ISSUE THREAD

**Issue by sayit135** [SecHex/SecHex-Spoofy#60]
![image](https://github.com/SecHex/SecHex-Spoofy/assets/35692406/953a2bef-f9a3-4ba9-9613-f368a8d5b2af)
It gives me such a line, but I downloaded it normally and installed steam.
![image](https://github.com/SecHex/SecHex-Spoofy/assets/35692406/1138f320-5b57-4e2e-a4b8-691aa35be6a5)
![image](https://github.com/SecHex/SecHex-Spoofy/assets/35692406/4dc94d7c-bf2a-432c-a2f4-e7953b0c6921)
![image](https://github.com/SecHex/SecHex-Spoofy/assets/35692406/cf1c5e0b-e25a-4d7a-82a9-4ad20dce6dbb)
not working

**Comment by SecHex** [comment]
Who said its a unbanning function for CFX.RE? Its just a Trace Cleaning function.
