### ISSUE TITLE
Does this work on fortnite because when i clean my pc and run all spoofers im still hwid banned

### ISSUE THREAD

**Issue by rathisgod** [SecHex/SecHex-Spoofy#7]

**Comment by Mehdzor** [comment]
@rathisgod, probably, because it only changes the registry keys. It might not be enough to fool 'Easy Anti-Cheat'.

**Comment by SecHex** [comment]
> @rathisgod, probably, because it only changes the registry keys. It might not be enough to fool 'Easy Anti-Cheat'.

Thats right.
