### ISSUE TITLE
mac address suggestion

### ISSUE THREAD

**Issue by aimrcheats** [SecHex/SecHex-Spoofy#81]
so i've used the mac changer twice - both times i used it, i had to switch my mac address back. the spoofer doesn't create a working mac address (i'd guess there's some sort of algorithm used for them) so i'd look into that

**Comment by SecHex** [comment]
Fixed in the latest update. 

https://github.com/SecHex/SecHex-Spoofy/releases/tag/V1.5.8-23.02.24
