### ISSUE TITLE
Never trust this tool

### ISSUE THREAD

**Issue by Rizky21ID** [SecHex/SecHex-Spoofy#82]
I have tried 3 times to use this tool, I hope you never use this fucking tool, I got malware and my Github account and Instagram got hacked, shit this f*cking tool

**Comment by SecHex** [comment]
alr "IT Security Enthusiast"

**Comment by scottjsh** [comment]
IT Security Enthusiast was hacked from SPOFER, not Melware, in GitHub
LMFAO😆😆
