### ISSUE TITLE
xbox socials bug

### ISSUE THREAD

**Issue by domnulX** [SecHex/SecHex-Spoofy#86]
after clicking the "terminate" xbox app button by pure curiosity, i unfortunately found myself needing to use the xbox socials once again to be able to talk to some of my old friends.
what i didnt know at the time is that i pretty much bricked it and even after multiple reinstallations and deleting reg keys (thats what msoft suggested doing in one of their bug reports), i was still unable to acces it.

are there any known fixes for this?

**Comment by SecHex** [comment]
Do you have some screenshots of the "error" messages?
